### ISSUE TITLE
No module named pgxnclient.cli

### ISSUE THREAD

**Issue by Karlodun** [pgxn/pgxnclient#32] opened 2018-08-09 09:33 UTC
fresh install in WSL. Any easy solutions?
As far as I understand the reference goes to pgxnclient/cli.py, and I can fix this.... but to fix it every time I am on a new computer or updating/reinstalling....

```
 # pgxn help --libexec
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pgxnclient/libexec/pgxn-help", line 10, in <module>
    from pgxnclient.cli import script
ImportError: No module named pgxnclient.cli
```

**Comment by arkangle** [comment] 2018-09-18 16:30
How did  you fix the reference issue?

**Comment by kspoon01** [comment] 2018-11-21 18:01
I ran into the same issue, how did you fix this issue?

**Comment by dvarrazzo** [comment] 2018-12-25 06:11
Can't reproduce the problem. I added a test to verify it. The problem might have been solved by the fact that now the codebase is 2 and 3 compatible. So it should be fixed in release 1.3. however I'd be interested to know how the module was installed. Thank you.

**Comment by shatteringlass** [comment] 2019-01-29 22:16
I have encountered this issue with the module installed today via pip3.

**Comment by fake-name** [comment] 2019-04-29 03:31
I just hit this issue. 

The problem is that the `pgxnclient` script is invoking the wrong python.

Basically, I have pgxnclient installed in python3. However, `pgxnclient/cli.py` invokes some of the subscripts (`libexec/pgxn-install`, in my case) via `os.execv()`, which then uses the shebang line in the subcommand to chose the runtime interpreter. 

The commands in `libexec/*` all have the shebang line of `#!/usr/bin/env python`, which then invokes python **2**, and immediately fails because it's the wrong python.

**Comment by dvarrazzo** [comment] 2019-04-29 07:02
Will look into it.

**Closed** 2019-04-29 23:41 UTC

**Comment by fake-name** [comment] 2019-04-29 23:46
Cool!

**Comment by dvarrazzo** [comment] 2019-04-29 23:50
@fake-name Np, but I should wrap a release sooner than later... Have to dust off and automate integration tests.

**Comment by fake-name** [comment] 2019-08-13 22:10
So this is still an issue, and I don't exactly fancy hand-fixing all the various sub-scripts. Any chance of a release?
